logging:
  level:
    root: WARN

management:
  endpoints:
    web:
      expose: "*"

spring:
  application:
    name: Spudnik
  datasource:
    url: "jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE"
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    open-in-view: false
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: "always"
